### ISSUE TITLE
broken elasticsearch output in v1.15 - undefined method `dig' for \"ok\":String"

### ISSUE THREAD

**Issue by genofire** [kube-logging/fluentd-images#33]
Not sure which images was taken as base - v1.15 used on 2023-04-27

```
time=2023-05-15 11:41:40 +0000 chunk="XXXXXXXXXXXX" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"http-logstash.SECRET.local\", :port=>443, :scheme=>\"https\", :user=>\"SECRET\", :password=>\"obfuscated\"}): undefined method `dig' for \"ok\":String"

```

**Comment by pepov** [comment]
can you help me understanding what is the problem here? can you give a yaml to reproduce?

**Comment by genofire** [comment]
I would next friday (not this) take a look in a new build together with #28 and give mor details with image tag and so on.

sorry, for the less good issue.

**Comment by genofire** [comment]
Found the "bug", the new elasticsearch-ruby validates more agressiv the endpoint (see #42 ), so your recieve endpoint (an logstash with http and codec es_bulk) does not work anymore.

one of the checks are an HTTP-GET where the response are an json object with version ... (but logstash only answer with `ok`, so this dig failed)
