### ISSUE TITLE
The aliyun oss plug-in does not work properly

### ISSUE THREAD

**Issue by xiaoluhong** [kube-logging/fluentd-images#49]
hello,

Learn from the documentation（https://kube-logging.dev/docs/configuration/plugins/outputs/oss/），the logging operator supports alyun oss. 

I provided access_key_id and access_key_secret，

https://kube-logging.dev/docs/configuration/plugins/outputs/oss/#output-config-access_key_id
https://kube-logging.dev/docs/configuration/plugins/outputs/oss/#output-config-aaccess_key_secret 

But configcheck pod displays error

```
2023-06-12 10:17:50 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="'oss_key_id' parameter is required"
```

The documentation says that the oss plug-in repo is https://github.com/aliyun/fluent-plugin-oss ，https://rubygems.org/gems/fluent-plugin-aliyun-oss. 
But, the aliyun repo plug-in version is 0.0.1，the fluentd docker images oss plugin shows 0.0.2 .

```
2023-06-12 10:11:08 +0000 [info]: gem 'fluent-plugin-oss' version '0.0.2'
```

I searched for another oss plugin repo https://github.com/jicong/fluent-plugin-oss，I see that the configuration example uses oss_key_id，and its latest version is 0.0.2. (https://rubygems.org/gems/fluent-plugin-oss/versions/0.0.2) 

So, the issue is the aliyun oss plugin does not match?

**Comment by pepov** [comment]
closing this as fixed by https://github.com/kube-logging/logging-operator/issues/1361, please feel free to reopen if that's not the case
