### ISSUE TITLE
OCI annotations for docker image

### ISSUE THREAD

**Issue by 24367dfa** [kube-logging/fluentd-images#75]
I propose to convert the LABELs in Dockerfile[^1] to OCI Annotations[^2].

Those would show up nicely rendered here: https://github.com/kube-logging/fluentd-images/pkgs/container/fluentd/128932176?tag=v1.15-staging

Possible implementations[^3]:

- adding labels in `.github/workflows/ci.yml`
- adding labels in `Dockerfile`

[^1]: https://github.com/kube-logging/fluentd-images/blob/main/v1.16/Dockerfile#L5
[^2]: https://github.com/opencontainers/image-spec/blob/main/annotations.md
[^3]: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images

**Comment by pepov** [comment]
I would recommend implementing this in the CI workflow, similar as it is being implemented for the operator:
https://github.com/kube-logging/logging-operator/pull/1511/files
