### ISSUE TITLE
Broken images with uninitialized constant OpenSearch::Transport::Transport::HTTP::Faraday::VERSION

### ISSUE THREAD

**Issue by sebastiangaiser** [kube-logging/fluentd-images#94]
Hey,

I'm currently having problems with the images complaining about `uninitialized constant OpenSearch::Transport::Transport::HTTP::Faraday::VERSION` which is an error from https://github.com/opensearch-project/opensearch-ruby/issues/205 and https://github.com/fluent/fluent-plugin-opensearch/pull/116. 

I tried `v1.15-ruby3-build.99`, `v1.15-ruby3-build.100` and `v1.15-ruby3` as the operators default for `4.2.2`.

@pepov or someone else, would it be possible for you to bump the versions accordingly and build new images (recognized that the v1.15 directory is already gone). 

Thanks in advance

**Comment by sebastiangaiser** [comment]
There is no release yet...
https://github.com/fluent/fluent-plugin-opensearch/issues/118

**Comment by sebastiangaiser** [comment]
```
fluentd:
  image:
    tag: v1.16-full-build.118
```

seams to work

**Comment by OverOrion** [comment]
Hey @sebastiangaiser,

As you already mentioned the v1.16 is the latest release and it will be the default version for a later logging operator release, if everything goes well then 4.5 will be shipped with it by default.

If you have further questions please reopen.
